/**
 * Renders seed stories as SQL for supabase/seed.sql.
 *
 * Upserts keyed on fixed ids and URLs, so running the file again refreshes the
 * rows (and their times) instead of failing on duplicates.
 */
import type { SeedOptions, SeedStory } from './generate.ts';

type SqlValue = string | number | null;

/** A SQL literal. Text doubles single quotes, which is all standard_conforming_strings needs. */
function literal(value: SqlValue): string {
  if (value === null) return 'null';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`seed: non-finite number ${value}`);
    return String(value);
  }
  return `'${value.replaceAll("'", "''")}'`;
}

/** An instant `seconds` before the moment the seed runs. */
function ago(seconds: number): string {
  return `now() - interval '${Math.round(seconds)} seconds'`;
}

function row(values: readonly string[]): string {
  return `  (${values.join(', ')})`;
}

const STORY_COLUMNS = [
  'id',
  'title',
  'summary',
  'category',
  'lat',
  'lon',
  'place_name',
  'place_source',
  'place_conf',
  'country_code',
  'heat',
  'sentiment',
  'source_count',
  'published_at',
  'first_seen_at',
  'discussion_state',
] as const;

const ARTICLE_COLUMNS = [
  'story_id',
  'url',
  'outlet',
  'outlet_country',
  'headline',
  'snippet',
  'published_at',
  'lang',
] as const;

function upsert(
  table: string,
  columns: readonly string[],
  key: string,
  rows: readonly string[],
): string {
  const updates = columns
    .filter((column) => column !== key)
    .map((column) => `  ${column} = excluded.${column}`);
  return [
    `insert into public.${table} (${columns.join(', ')})`,
    'values',
    rows.join(',\n'),
    `on conflict (${key}) do update set`,
    `${updates.join(',\n')};`,
  ].join('\n');
}

export function seedSql(stories: readonly SeedStory[], options: SeedOptions): string {
  const storyRows = stories.map((s) =>
    row([
      literal(s.id),
      literal(s.title),
      literal(s.summary),
      literal(s.category),
      literal(s.place.lat),
      literal(s.place.lon),
      literal(s.placeName),
      literal(s.placeSource),
      literal(s.placeConf),
      literal(s.place.code),
      literal(s.heat),
      literal(s.sentiment),
      literal(s.articles.length),
      ago(s.ageSec),
      ago(s.firstSeenAgeSec),
      literal(s.discussionState),
    ]),
  );

  const articleRows = stories.flatMap((s) =>
    s.articles.map((a) =>
      row([
        literal(s.id),
        literal(a.url),
        literal(a.outlet),
        literal(a.outletCountry),
        literal(a.headline),
        literal(a.snippet),
        ago(a.ageSec),
        literal('en'),
      ]),
    ),
  );

  return [
    `-- Local development seed: ${stories.length} fictional stories across the globe and the last`,
    `-- ${options.windowHours} hours, with ${articleRows.length} articles.`,
    '--',
    '-- GENERATED by scripts/seed/generate.ts (npm run db:seed:generate). Do not edit by hand;',
    '-- tests/seed.test.ts fails if this file and the generator disagree.',
    '--',
    '-- Cities are real; events and outlets are invented. Every outlet uses the reserved',
    '-- .example domain, so no link leads anywhere. Times are relative to now(), so',
    '-- `npm run db:reset` always yields a fresh window. `supabase db push` does not send',
    '-- this file to a hosted project unless --include-seed is passed.',
    '',
    upsert('stories', STORY_COLUMNS, 'id', storyRows),
    '',
    upsert('articles', ARTICLE_COLUMNS, 'url', articleRows),
    '',
  ].join('\n');
}
