/**
 * Downloads the public-domain Earth textures into public/textures/_source/,
 * then writes public/textures/SOURCES.md recording where each one came from.
 *
 * Usage:
 *   npm run textures:fetch            # skips files already present
 *   npm run textures:fetch -- --force # re-downloads everything
 *
 * The source files total ~36MB and are gitignored. Run this once after cloning,
 * then `npm run textures:build` to generate the tier variants.
 */
import { createWriteStream } from 'node:fs';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { Readable } from 'node:stream';
import type { ReadableStream as NodeWebReadableStream } from 'node:stream/web';
import { pipeline } from 'node:stream/promises';
import { fileURLToPath } from 'node:url';

import { SOURCE_DIR, TEXTURE_SOURCES, type TextureSource } from './textures.config.ts';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');

function mb(bytes: number): string {
  return `${(bytes / 1_048_576).toFixed(1)}MB`;
}

async function fileSize(path: string): Promise<number | null> {
  try {
    return (await stat(path)).size;
  } catch {
    return null;
  }
}

async function download(source: TextureSource): Promise<void> {
  const target = join(repoRoot, SOURCE_DIR, source.file);
  const existing = await fileSize(target);

  if (existing !== null && !force) {
    console.log(`  ${source.id.padEnd(7)} skip — already present (${mb(existing)})`);
    return;
  }

  process.stdout.write(`  ${source.id.padEnd(7)} downloading ~${mb(source.approxBytes)} … `);

  const response = await fetch(source.url, { redirect: 'follow' });
  if (!response.ok || response.body === null) {
    throw new Error(`${source.id}: HTTP ${response.status} from ${source.url}`);
  }

  // Stream to a .part file so an interrupted run never leaves a truncated
  // texture that looks valid to the next run's skip check.
  const partial = `${target}.part`;
  // fetch() returns a DOM ReadableStream; @types/node types Readable.fromWeb
  // against node:stream/web's. Structurally identical at runtime, so cast.
  await pipeline(
    Readable.fromWeb(response.body as NodeWebReadableStream<Uint8Array>),
    createWriteStream(partial),
  );

  const written = await fileSize(partial);
  if (written === null || written < source.approxBytes * 0.5) {
    await rm(partial, { force: true });
    throw new Error(
      `${source.id}: download looks truncated (${written ?? 0} bytes, expected ~${source.approxBytes})`,
    );
  }

  await rm(target, { force: true });
  const { rename } = await import('node:fs/promises');
  await rename(partial, target);
  console.log(`done (${mb(written)})`);
}

function sourcesMarkdown(): string {
  const rows = TEXTURE_SOURCES.map(
    (s) =>
      `| \`${s.file}\` | ${s.width}×${s.height} | ${s.credit} | [source page](${s.sourcePage}) |`,
  ).join('\n');

  const details = TEXTURE_SOURCES.map(
    (s) =>
      `### ${s.id}\n\n- **URL:** ${s.url}\n- **Credit:** ${s.credit}\n- **Notes:** ${s.notes}\n`,
  ).join('\n');

  return `# Texture sources

Generated by \`scripts/fetch-textures.ts\`. Do not edit by hand — edit
\`scripts/textures.config.ts\` and re-run \`npm run textures:fetch\`.

All imagery here is **public domain** under [NASA's media usage policy](https://www.nasa.gov/nasa-brand-center/images-and-media/).
NASA does not require permission or a licence fee. Credit is given below as a
courtesy and because the policy asks that NASA not be shown to endorse anything.
No source here needs an API key.

| File | Native size | Credit | Source |
| --- | --- | --- | --- |
${rows}

## Derived files

\`specular-*.webp\` is **not a NASA product.** It is generated locally by
\`scripts/process-textures.ts\` from the Blue Marble topography/bathymetry map by
thresholding ocean blue, because NASA no longer publishes a standalone
land/water mask. It inherits the day map's public-domain status as a derivative.

\`clouds-*.webp\` gains its alpha channel locally: the published cloud composite
is an opaque JPEG, so luminance is moved into the alpha channel and the colour
channels are flattened to white.

## Details

${details}
`;
}

async function main(): Promise<void> {
  console.log(`Fetching ${TEXTURE_SOURCES.length} textures into ${SOURCE_DIR}/`);
  await mkdir(join(repoRoot, SOURCE_DIR), { recursive: true });

  for (const source of TEXTURE_SOURCES) {
    await download(source);
  }

  const sourcesPath = join(repoRoot, 'public/textures/SOURCES.md');
  await writeFile(sourcesPath, sourcesMarkdown(), 'utf8');
  console.log(`\nWrote public/textures/SOURCES.md`);
  console.log(`Next: npm run textures:build`);
}

main().catch((error: unknown) => {
  console.error(`\nfetch-textures failed: ${error instanceof Error ? error.message : error}`);
  process.exitCode = 1;
});
