/**
 * Regenerates the ingest Worker's reference data:
 *
 *   npm run ingest:data
 *
 * 1. workers/ingest/src/data/fips.ts: FIPS 10-4 -> ISO 3166-1 alpha-2, from
 *    GeoNames countryInfo.txt (CC BY 4.0, https://www.geonames.org/). GDELT
 *    locations use FIPS, where `AS` is Australia and `AU` is Austria; our
 *    country_code columns are ISO.
 * 2. workers/ingest/src/data/outlet-countries.txt: news domain -> ISO country,
 *    from GDELT's domain list (https://blog.gdeltproject.org/, May 2018 update;
 *    GDELT data is free for any use with attribution). Only domains whose
 *    country the TLD cannot tell us are kept (.com, .org, and vanity ccTLDs
 *    such as .tv); a domain like thehindu.co.in is resolved by its TLD instead.
 */

import { mkdirSync, writeFileSync } from 'node:fs';

import { VANITY_TLDS } from '../../workers/ingest/src/normalize/outlets.ts';

const GEONAMES_URL = 'https://download.geonames.org/export/dump/countryInfo.txt';
const DOMAINS_URL =
  'https://data.gdeltproject.org/blog/2018-news-outlets-by-country-may2018-update/MASTER-GDELTDOMAINSBYCOUNTRY-MAY2018.TXT';
const OUT_DIR = 'workers/ingest/src/data';

async function download(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return response.text();
}

// --- FIPS -> ISO -----------------------------------------------------------
const fipsToIso = new Map<string, string>();
for (const line of (await download(GEONAMES_URL)).split('\n')) {
  if (line.startsWith('#') || line.trim() === '') continue;
  const [iso, , , fips] = line.split('\t');
  if (
    iso !== undefined &&
    fips !== undefined &&
    /^[A-Z]{2}$/.test(iso) &&
    /^[A-Z]{2}$/.test(fips)
  ) {
    fipsToIso.set(fips, iso);
  }
}

const entries = [...fipsToIso].sort(([a], [b]) => a.localeCompare(b));
const fipsModule = `/**
 * FIPS 10-4 country code -> ISO 3166-1 alpha-2. Generated by
 * scripts/ingest/build-data.ts from GeoNames countryInfo.txt
 * (https://www.geonames.org/, CC BY 4.0). Do not edit by hand.
 */
export const FIPS_TO_ISO: Readonly<Record<string, string>> = {
${entries.map(([fips, iso]) => `  ${fips}: '${iso}',`).join('\n')}
};
`;

// --- Outlet domains -> ISO -------------------------------------------------
const outlets: string[] = [];
let unmapped = 0;
for (const line of (await download(DOMAINS_URL)).split('\n')) {
  const [rawDomain, fips] = line.split('\t');
  const domain = rawDomain?.trim().toLowerCase();
  if (domain === undefined || domain === '' || fips === undefined) continue;
  const tld = domain.slice(domain.lastIndexOf('.') + 1);
  if (tld.length === 2 && !VANITY_TLDS.has(tld)) continue;
  const iso = fipsToIso.get(fips.trim());
  if (iso === undefined) {
    unmapped++;
    continue;
  }
  outlets.push(`${domain}\t${iso}`);
}
outlets.sort();

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(`${OUT_DIR}/fips.ts`, fipsModule);
writeFileSync(`${OUT_DIR}/outlet-countries.txt`, outlets.join('\n') + '\n');
console.log(`fips.ts: ${entries.length} codes`);
console.log(
  `outlet-countries.txt: ${outlets.length} domains (${unmapped} with no ISO code skipped)`,
);
