/**
 * Regenerates workers/ingest/src/data/common-keys.ts: event keys so frequent
 * across unrelated coverage that sharing one says nothing about the event.
 *
 *   node --experimental-strip-types scripts/ingest/common-keys.ts [--end SLOT] [--slots N] [--every N]
 *
 * A key is common when at least 1% of all write-ups in the sample carry it
 * (never fewer than 20). Counting write-ups rather than articles keeps a
 * story syndicated to 40 papers from counting 40 times.
 *
 * The sample is one slot every 3 hours for a week. A contiguous few hours
 * does not work: that day's biggest story dominates it, and its keys (the
 * judge in the 2026-09-24 White House ruling, `p:t kelly`, crossed 1% of a
 * four-hour sample) are exactly the ones that identify an event.
 */

import { writeFileSync } from 'node:fs';

import { groupWriteups } from '../../workers/ingest/src/dedup/cluster.ts';
import { createFeed } from '../../workers/ingest/src/gdelt/feed.ts';
import { parseGkg } from '../../workers/ingest/src/gdelt/gkg.ts';
import { previousSlot } from '../../workers/ingest/src/gdelt/slots.ts';
import { normalizeRecord, type IngestArticle } from '../../workers/ingest/src/normalize/article.ts';

const OUT = 'workers/ingest/src/data/common-keys.ts';
const SHARE = 0.01;
const FLOOR = 20;

function arg(name: string, fallback: string): string {
  const at = process.argv.indexOf(name);
  return at >= 0 ? (process.argv[at + 1] ?? fallback) : fallback;
}

const end = arg('--end', '20260924084500');
const count = Number(arg('--slots', '56'));
const every = Number(arg('--every', '12'));
const slots: string[] = [end];
while (slots.length < count) {
  let slot = slots[0] ?? end;
  for (let i = 0; i < every; i++) slot = previousSlot(slot);
  slots.unshift(slot);
}

const feed = createFeed('https://data.gdeltproject.org/gdeltv2');
const frequency = new Map<string, number>();
let writeupCount = 0;

for (const slot of slots) {
  const file = await feed.fetchSlot(slot);
  if (file === null) {
    console.warn(`${slot}: not published, skipped`);
    continue;
  }
  const articles = parseGkg(file.text).records.flatMap((record): IngestArticle[] => {
    const result = normalizeRecord(record, { outletCountry: () => null });
    return result.ok ? [result.article] : [];
  });
  const { writeups } = groupWriteups(articles, new Set());
  writeupCount += writeups.length;
  for (const writeup of writeups) {
    for (const key of writeup.keys) frequency.set(key, (frequency.get(key) ?? 0) + 1);
  }
  console.log(`${slot}: ${articles.length} articles, ${writeups.length} write-ups`);
}

const threshold = Math.max(FLOOR, Math.ceil(writeupCount * SHARE));
const common = [...frequency]
  .filter(([, n]) => n >= threshold)
  .sort(([a], [b]) => (a < b ? -1 : 1))
  .map(([key]) => key);

writeFileSync(
  OUT,
  `/**
 * Event keys too common to identify an event: each was carried by at least
 * ${threshold} of ${writeupCount} write-ups (1%) in the English GKG feed, sampled every
 * ${every * 15} minutes from ${slots[0]} to ${end} UTC (${slots.length} slots).
 * Generated by scripts/ingest/common-keys.ts; do not edit by hand.
 */
export const COMMON_KEYS: ReadonlySet<string> = new Set([
${common.map((key) => `  ${JSON.stringify(key)},`).join('\n')}
]);
`,
);
console.log(`${OUT}: ${common.length} keys at >= ${threshold} of ${writeupCount} write-ups`);
